export const CATEGORIES = [
  'Patience',
  'Gratitude',
  'Family',
  'Work',
  'Anger',
  'Honesty',
  'Kindness',
  'Reflection',
  'Sabr',
  'Tawakkul',
] as const;

export type Category = (typeof CATEGORIES)[number];

export interface ApplicationLog {
  id: string;
  verseKey: string;
  logText: string;
  categories: Category[];
  voiceTranscript?: string;
  voiceNoteUrl?: string;
  createdAt: string;
  collectionItemId: string;
}

export interface NoteMetadata {
  v: number;
  app: string;
  verseKey: string;
  categories: Category[];
  voiceTranscript: string | null;
  date: string;
  appVersion?: string;
  type?: 'journal' | 'whisper';
  challenge?: string;
  /** Poetic one-sentence Echo generated by LLM at save time */
  echo?: string;
}

export interface ParsedNote {
  logText: string;
  metadata: NoteMetadata | null;
}
