'use client';

import { useState } from 'react';
import { FileDown, Loader2 } from 'lucide-react';
import { format } from 'date-fns';
import { Button } from '@/components/ui/button';
import { parseNoteBody } from '@/lib/utils';

interface Note {
  id: string;
  body: string;
  createdAt: string;
}

export function PdfExportButton({ notes }: { notes: Note[] }) {
  const [isExporting, setIsExporting] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    try {
      const [{ default: jsPDF }, { default: html2canvas }] = await Promise.all([
        import('jspdf'),
        import('html2canvas')
      ]);

      const container = document.createElement('div');
      container.id = 'journal-print-area';
      container.style.position = 'absolute';
      container.style.left = '-9999px';
      container.style.top = '-9999px';
      container.style.width = '800px';
      container.style.padding = '40px';
      container.style.backgroundColor = '#f8f1e3';
      container.style.color = '#1c160f';
      container.style.fontFamily = 'system-ui, sans-serif';

      const appNotes = notes.filter(n => n.body.includes('<!--aia'));
      
      let html = `
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="font-family: 'Amiri', serif; font-size: 36px; color: #0a6650; margin: 0;">My Quran Journal</h1>
          <p style="color: #7a6a50; margin-top: 8px;">Exported on ${format(new Date(), 'MMMM d, yyyy')}</p>
        </div>
      `;

      html += '<div style="display: flex; flex-direction: column; gap: 32px;">';
      
      appNotes.forEach(note => {
        const { logText, metadata } = parseNoteBody(note.body);
        const categories = metadata?.categories || [];
        const dateStr = format(new Date(note.createdAt), 'EEEE, d MMMM yyyy');
        const verseKey = metadata?.verseKey || 'Unknown Verse';
        
        html += `
          <div style="border: 1px solid #dcd0b0; padding: 24px; border-radius: 12px; background: #fff;">
            <div style="display: flex; justify-content: space-between; margin-bottom: 16px; align-items: baseline;">
              <div style="font-weight: bold; color: #0a6650;">${verseKey}</div>
              <div style="color: #7a6a50; font-style: italic; font-size: 14px; opacity: 0.8; transform: rotate(-1deg);">${dateStr}</div>
            </div>
            <p style="line-height: 1.6; white-space: pre-wrap;">${logText}</p>
            ${categories.length > 0 ? `
              <div style="margin-top: 16px; display: flex; gap: 8px; flex-wrap: wrap;">
                ${categories.map((c: string) => `<span style="background: #efe8d6; padding: 4px 10px; border-radius: 16px; font-size: 12px; color: #7a6a50;">${c}</span>`).join('')}
              </div>
            ` : ''}
          </div>
        `;
      });

      if (appNotes.length === 0) {
        html += `<p style="text-align: center; color: #7a6a50; font-style: italic;">No journal entries yet.</p>`;
      }

      html += '</div>';
      
      html += `
        <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #7a6a50;">
          Generated by Ayah in Action — ayahinaction.app
        </div>
      `;

      container.innerHTML = html;
      document.body.appendChild(container);

      const canvas = await html2canvas(container, { scale: 2, useCORS: true });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
      
      const pageWidth = pdf.internal.pageSize.getWidth();
      const imgHeight = (canvas.height * pageWidth) / canvas.width;
      let heightLeft = imgHeight;
      let position = 0;
      
      pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
      heightLeft -= 297;
      
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, imgHeight);
        heightLeft -= 297;
      }
      
      pdf.save(`quran-journal-${format(new Date(), 'yyyy-MM-dd')}.pdf`);
      document.body.removeChild(container);
    } catch (err) {
      console.error('Failed to export PDF:', err);
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button onClick={handleExport} disabled={isExporting} variant="outline" className="gap-2">
      {isExporting ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
      <span>{isExporting ? 'Exporting...' : 'Export My Quran Journal'}</span>
    </Button>
  );
}
